#!/bin/bash
function usage {
    echo "usage: $(basename $0) {start|stop|restart}" 1>&2
}

. /etc/rc.conf
. /etc/rc.d/functions

name=aionis
bin_dir="$(dirname "$(realpath $0)")"
daemon=aionis-daemon
daemon_bin="${bin_dir}/${daemon}"
ARGS=

[[ -r "/etc/conf.d/${daemon}" ]] && . "/etc/conf.d/${daemon}"

PID="$(pgrep "${daemon}")"
function spawn-aionis {
    "${daemon_bin}" "$@" &> /dev/null < /dev/null &
    disown
}

case $1 in
    (start)
        stat_busy "Starting ${name}"
        if [[ -z "${PID}" ]]; then
            spawn-aionis ${ARGS} &> /dev/null
            if [[ "$?" -eq 0 ]]; then
                add_daemon "${name}"
                stat_done
            else
                stat_fail
                exit 1
            fi
        fi
        ;;
    (stop)
        stat_busy "Stopping ${name}"
        if [[ -n "${PID}" ]]; then
            kill "${PID}" &> /dev/null
            if [[ "$?" -eq 0 ]]; then
                stat_done
            else
                stat_fail
                exit 1
            fi
        fi
        ;;
    (restart)
        "$0" stop
        sleep 1
        "$0" start
        ;;
    (*)
        usage
        exit 1
        ;;
esac
