#!/usr/bin/env zsh

function usage {
    echo "usage: $(basename $0)" 1>&2
    echo "must be run as root" 1>&2
}

[[ $# -eq 0 ]] || { usage; exit 1; }
[[ $(whoami) == root ]] || { usage; exit 1; }

aionis_root_dir=$(dirname "$(realpath $0)")
systemd_conf_dir=/etc/systemd/system
bin_dir=/usr/bin
aionis_data_dir=/usr/share/aionis

cp ${aionis_root_dir}/aionis.service ${systemd_conf_dir}/
cp ${aionis_root_dir}/aionis-daemon ${bin_dir}/
if [[ ! -d ${aionis_data_dir}/ ]]; then
    mkdir ${aionis_data_dir}/
fi
cp ${aionis_root_dir}/zelos.jpg ${aionis_data_dir}/
